---
- name: Dist-Upgrade
  apt:
    upgrade: dist
    autoremove: yes
    update_cache: yes
    autoclean: yes

- name: Install software
  apt:
    name:
    - ufw
    - monit
    - exim4
    state: present
