---
- name: Set up login banner file
  copy:
    src: ../files/issue.net
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644

# The following stanzas are based on:
# https://wiki.debian.org/motd
# https://oitibs.com/debian-jessie-dynamic-motd/

- name: Set up the MOTD updater path
  file:
    name: /etc/update-motd.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Stop /etc/init.d/motd from running
  systemd:
    name: motd
    enabled: no
    state: stopped
    masked: yes

- name: Ensure the MOTD updater has the right scripts
  copy:
    src: ../files/update-motd.d/
    dest: /etc/update-motd.d/
    owner: root
    group: root
    mode: 0755

- name: Ensure the MOTD is found in the right path
  file:
    name: /etc/motd
    state: link
    src: /var/run/motd
    force: yes
    owner: root
    group: root
    mode: 0644

- name: Update /etc/pam.d/sshd to run the update-motd.d
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    insertbefore: '^\s*session    optional     pam_motd.so  motd=/run/motd.dynamic\s*$'
    line: "session    optional     pam_exec.so  type=open_session stdout /bin/run-parts /etc/update-motd.d"
