---
- name: Install software
  apt:
    name:
    - monit
    - ssl-cert
    state: present

- name: Build TLS cert+key
  shell: cat ssl-cert-snakeoil.key ../certs/ssl-cert-snakeoil.pem > final-ssl-cert-snakeoil.pem
  args:
    chdir: /etc/ssl/private/
    creates: final-ssl-cert-snakeoil.pem
  when: certbot_pem is not defined

- name: Set TLS certificate to 0600
  file:
    path: "{{ certbot_pem | default('/etc/ssl/private/final-ssl-cert-snakeoil.pem') }}"
    mode: "0600"

- name: Ensure config directory exists
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  with_items:
  - "/etc/monit"
  - "/etc/monit/conf.d"

- name: Set up config files
  template:
    src: "../templates/monit_conf.d/{{ item }}.j2"
    dest: "/etc/monit/conf.d/{{ item }}"
    owner: root
    group: root
    mode: "0600"
  with_items:
  - daemon
  - host
  - notify
  - httpd
  - filesystem
  - cron
  - exim4
  - fail2ban
  - ntp
  notify: Restart Monit

- name: Configure Firewall
  ufw:
    port: "{{ monit_https_port | default(2812) }}"
    proto: tcp
    rule: in
    insert: 1
    comment: "Monit HTTPS"
  notify: Reload UFW
